api_key:    # CloudOne API key (On Cloud One console go to Administration->API Keys->New)
region:     # CloudOne region (On Cloud One console go to Administration-Account Settings->Region)
account_id: # CloudOne account ID (On Cloud One console go to Administration-Account Settings->ID)
aws_region: # AWS region, i.e. us-east-1
