// Code generated by enum (github.com/mpkondrashin/enum) using following command:
// enum -package cone -type Action --names bypass,inspect
// DO NOT EDIT!

package cone

import (
    "encoding/json"
 "encoding/xml"
    "errors"
    "fmt"
    "strconv"
    "strings"
)

type Action int

const (
    ActionBypass  Action = iota
    ActionInspect Action = iota
)


// String - return string representation for Action value
func (v Action)String() string {
    s, ok := map[Action]string {
         ActionBypass:  "bypass",
         ActionInspect: "inspect",
    }[v]
    if ok {
        return s
    }
    return "Action(" + strconv.FormatInt(int64(v), 10) + ")"
}

// ErrUnknownAction - will be returned wrapped when parsing string
// containing unrecognized value.
var ErrUnknownAction = errors.New("unknown Action")


var mapActionFromString = map[string]Action{
    "bypass":    ActionBypass,
    "inspect":    ActionInspect,
}

// UnmarshalJSON implements the Unmarshaler interface of the json package for Action.
func (s *Action) UnmarshalJSON(data []byte) error {
    var v string
    if err := json.Unmarshal(data, &v); err != nil {
        return err
    }
    result, ok := mapActionFromString[strings.ToLower(v)]
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownAction, v)
    }
    *s = result
    return nil
}

// MarshalJSON implements the Marshaler interface of the json package for Action.
func (s Action) MarshalJSON() ([]byte, error) {
    return []byte(fmt.Sprintf("\"%v\"", s)), nil
}

// UnmarshalYAML implements the Unmarshaler interface of the yaml.v3 package for Action.
func (s *Action) UnmarshalYAML(unmarshal func(interface{}) error) error {
    var v string
    if err := unmarshal(&v); err != nil {
        return err
    }
    result, ok := mapActionFromString[strings.ToLower(v)]  
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownAction, v)
    }
    *s = result
    return nil
}


// MarshalXML implements the Marshaler interface of the xml package for Action.
func (s Action)  MarshalXML(e *xml.Encoder, start xml.StartElement) error {
 return e.EncodeElement(s.String(), start)
}

// UnmarshalXML implements the Unmarshaler interface of the xml package for Action.
func (s *Action) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
 var v string
 err := d.DecodeElement(&v, &start)
 if err != nil {
  return err
 }
 result, ok := mapActionFromString[strings.ToLower(v)]  
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownAction, v)
    }
 *s = result
 return nil
}

