name: Inspection Windows Build
on: [push]
permissions:
  contents: write
jobs:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v3

        - name: Run Tests
          run: got test -v ./cmg/ginspection

        - name: Build GInspection for Windows
          run: go build ./cmd/ginspection
        