name: Inspection Windows Build
on: [push]
permissions:
  contents: write
jobs:
    build:
      runs-on: windows-latest
      steps:

        - uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v3

        - name: Build GInspection for Windows
          run: go build -ldflags "-H windowsgui" ./cmd/ginspection

        - name: Install fyne
          run: go install fyne.io/fyne/v2/cmd/fyne@latest

        - name: Package
          run: fyne --os windows --executable ginspection.exe --name GInspection --appVersion ${{ github.ref_name }}  --icon ./bin/icon.png --release

        - name: Build Inspection for Windows
          run: go build ./cmd/inspection
    
        - name: Pack for Windows
          if: startsWith(github.ref, 'refs/tags/')
          run: Compress-Archive -Path bin/opengl32.dll, inspection.exe, ginspection.exe, README.md, config_example.yaml -Destination inspection_win64_${{ github.ref_name }}.zip
    
        - name: Release
          uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              inspection_win64_${{ github.ref_name }}.zip
      
      