name: Inspection Windows Build
on:
  push:
    tags:
    - '*'  
permissions:
  contents: write
jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [windows-latest, macos-latest, ubuntu-latest]
      steps:

        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v3

        - name: setup env
          run: |
            echo "::set-env name=GOPATH::$(go env GOPATH)"
            echo "::add-path::$(go env GOPATH)/bin"
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

        - name: Install fyne
          run: go install fyne.io/fyne/v2/cmd/fyne@latest
        
        - name: Package
          if: startsWith(github.ref, 'refs/tags/') 
          run: fyne package --os ${{ matrix.os }} --name GInspection --appID in.kondrash --appVersion  "${${{ github.ref_name }}:1}" --icon ../../bin/icon.png --release --sourceDir ./cmd/ginspection

        - name: Get-ChildItem -Recurse
          if: matrix.os == 'windows'
          run: Get-ChildItem -Recurse

        - name: ls -lR
          if: matrix.os == 'macos' || matrix.os == 'ubuntu'
          run: ls -lR

        - name: Build Inspection
          run: go build ./cmd/inspection
    
        - name: Pack for Windows
          if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows'
          run: Compress-Archive -Path bin/opengl32.dll, inspection.exe, cmd/ginspection/GInspection.exe, README.md, config_example.yaml -Destination inspection_${{ matrix.os }}_${{ github.ref_name }}.zip

        - name: Pack for Linux and macOS
          if: startsWith(github.ref, 'refs/tags/') && (matrix.os == 'ubuntu' || matrix.os == 'macos')
          run: zip inspection_${{ matrix.os }}_${{ github.ref_name }}.zip inspection cmd/ginspection/GInspection README.md config_example.yaml

        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              inspection_${{ matrix.os }}_${{ github.ref_name }}.zip
      
      